const a = {
  nav: {
    dashboard: 'Painel',
    cars: 'Viaturas',
    reviews: 'Avaliações',
    leads: 'Pedidos',
    signOut: 'Terminar sessão',
  },

  leads: {
    title: 'Pedidos do site',
    subtitle: n => `${n} pedido${n !== 1 ? 's' : ''} recebido${n !== 1 ? 's' : ''}`,
    failedToLoad: 'Erro ao carregar pedidos:',
    empty: 'Ainda não há pedidos.',
    all: 'Todos',
    colDate: 'Data',
    colSource: 'Origem',
    colName: 'Nome',
    colContact: 'Contacto',
    colMessage: 'Mensagem',
    car: 'Viatura',
  },

  reviews: {
    title: 'Avaliações de Clientes',
    subtitle: n => `${n} avaliaç${n !== 1 ? 'ões' : 'ão'} na base de dados`,
    add: 'Adicionar Avaliação',
    edit: 'Editar',
    delete: 'Eliminar',
    loading: 'A carregar avaliações…',
    failedToLoad: 'Erro ao carregar avaliações:',
    empty: 'Sem avaliações ainda.',
    addFirst: 'Adicione a primeira avaliação',
    colClient: 'Cliente',
    colReview: 'Avaliação',
    colRating: 'Classificação',
    colLang: 'Idioma',
    colStatus: 'Estado',
    colActions: 'Ações',

    titleAdd: 'Adicionar Avaliação',
    titleEdit: 'Editar Avaliação',
    fName: 'Nome do Cliente',
    fNamePlaceholder: 'ex.: João S.',
    fLocation: 'Localização',
    fLocationPlaceholder: 'ex.: Lisboa, Portugal',
    fText: 'Texto da Avaliação (por idioma)',
    textHint: 'Preencha PT, EN e UA. Idiomas vazios usam o texto em PT.',
    fTitle: 'Título',
    fTitlePlaceholder: 'ex.: BMW entregue no Porto',
    fQuote: 'Comentário',
    fQuotePlaceholder: 'O que o cliente disse…',
    fRating: 'Classificação',
    fBadge: 'Etiqueta (carro · cidade)',
    fBadgePlaceholder: 'ex.: BMW · Porto',
    fLang: 'Idioma',
    langAll: 'Todos os idiomas',
    langPt: 'Português',
    langEn: 'Inglês',
    langUk: 'Ucraniano',
    fStatus: 'Estado',
    statusVisible: 'Visível no site',
    statusHidden: 'Oculta',
    fSortOrder: 'Ordem',
    fSortOrderHint: 'Número menor aparece primeiro',
    fImage: 'Foto / Avatar',
    uploadImage: 'Carregar Foto',
    uploading: 'A carregar…',
    removeImage: 'Remover foto',
    noImage: 'Sem foto — será usada a inicial do nome',
    save: 'Guardar',
    saving: 'A guardar…',
    create: 'Criar Avaliação',
    cancel: 'Cancelar',
    savedOk: 'Avaliação guardada',
    saveFailed: 'Erro ao guardar avaliação',
    deleted: 'Avaliação eliminada',
    deleteFailed: 'Erro ao eliminar',
    deleteTitle: 'Eliminar Avaliação',
    deleteConfirm: name => `Tem a certeza que quer eliminar a avaliação de ${name || 'este cliente'}?`,
    deleteWarning: 'Esta ação não pode ser desfeita.',
    deletePermanently: 'Eliminar permanentemente',
    errName: 'Nome obrigatório',
    uploadFailed: e => `Erro ao carregar: ${e}`,
    visible: 'Visível',
    hidden: 'Oculta',
  },

  login: {
    title: 'Entrar',
    email: 'Email',
    emailPlaceholder: 'admin@turboeagle.pt',
    password: 'Palavra-passe',
    submit: 'Entrar',
    submitting: 'A entrar…',
    back: '← Voltar ao site',
    errEmailRequired: 'Email obrigatório',
    errEmailInvalid: 'Introduza um endereço de email válido',
    errPasswordRequired: 'Palavra-passe obrigatória',
    errInvalid: 'Email ou palavra-passe inválidos',
  },

  dashboard: {
    title: 'Painel',
    subtitle: 'Resumo do inventário',
    addCar: 'Adicionar Viatura',
    total: 'Total de Viaturas',
    available: 'Disponível',
    reserved: 'Reservada',
    sold: 'Vendida',
    hidden: 'Oculta',
    failedToLoad: 'Erro ao carregar dados:',
    recentCars: 'Viaturas Recentes',
    viewAll: 'Ver todas →',
    loading: 'A carregar…',
    noCars: 'Sem viaturas.',
    addFirst: 'Adicione a primeira viatura',
    colCar: 'Viatura',
    colYear: 'Ano',
    colPrice: 'Preço',
    colStatus: 'Estado',
    edit: 'Editar',
  },

  list: {
    title: 'Viaturas',
    subtitle: n => `${n} viatura${n !== 1 ? 's' : ''} na base de dados`,
    filterActive: s => ` · filtro «${s}» ativo`,
    addCar: 'Adicionar Viatura',
    optimize: 'Otimizar fotos',
    optimizing: (done, total) => `A otimizar… ${done}/${total}`,
    optimizeHint: 'Comprime todas as fotos guardadas para o site carregar mais rápido',
    optimizeDone: n => `Fotos otimizadas em ${n} viatura${n !== 1 ? 's' : ''}`,
    search: 'Pesquisar marca, modelo, ano…',
    all: 'Todas',
    available: 'Disponível',
    reserved: 'Reservada',
    sold: 'Vendida',
    hidden: 'Oculta',
    failedToLoad: 'Erro ao carregar viaturas:',
    loading: 'A carregar viaturas…',
    noMatch: 'Nenhuma viatura corresponde aos filtros.',
    noCars: 'Sem viaturas.',
    addFirst: 'Adicione a primeira viatura',
    colCar: 'Viatura',
    colYear: 'Ano',
    colPrice: 'Preço',
    colMileage: 'Quilómetros',
    colStatus: 'Estado',
    colActions: 'Ações',
    edit: 'Editar',
    delete: 'Eliminar',
    statusUpdated: 'Estado atualizado',
    statusFailed: 'Erro ao atualizar estado',
    carDeleted: 'Viatura eliminada',
    deleteFailed: 'Erro ao eliminar viatura',
    deleteTitle: 'Eliminar Viatura',
    deleteConfirm: name => `Tem a certeza que quer eliminar permanentemente ${name}?`,
    deleteWarning: 'Esta ação não pode ser desfeita.',
    cancel: 'Cancelar',
    deletePermanently: 'Eliminar permanentemente',
  },

  status: {
    available: 'Disponível',
    reserved: 'Reservada',
    sold: 'Vendida',
    hidden: 'Oculta',
  },

  form: {
    backToCars: '← Viaturas',
    titleEdit: 'Editar Viatura',
    titleAdd: 'Adicionar Viatura',
    errorCount: n => `⚠ ${n} campo${n !== 1 ? 's' : ''} com atenção necessária`,
    cancel: 'Cancelar',
    save: 'Guardar Alterações',
    create: 'Criar Viatura',
    saving: 'A guardar…',
    loading: 'A carregar dados da viatura…',

    sBasicInfo: 'Informação Básica',
    sPricing: 'Preço',
    sTech: 'Especificações Técnicas',
    sAppearance: 'Aparência',
    sOptions: 'Opções e Serviços',
    sDescriptions: 'Descrições',
    sEquipment: 'Equipamento e Destaques',
    sGallery: 'Galeria e Imagens',
    sSEO: 'SEO',

    brand: 'Marca',
    brandPlaceholder: 'ex.: BMW',
    model: 'Modelo',
    modelPlaceholder: 'ex.: i4',
    version: 'Versão / Acabamento',
    versionPlaceholder: 'ex.: eDrive40 M Sport',
    year: 'Ano',
    status: 'Estado',
    statusAvailable: 'Disponível — visível no catálogo',
    statusReserved: 'Reservada — visível, marcada como reservada',
    statusSold: 'Vendida — visível, marcada como vendida',
    statusHidden: 'Oculta — não visível para visitantes',

    price: 'Preço (€)',
    pricePlaceholder: 'ex.: 54990',
    mileage: 'Quilómetros (km)',
    mileagePlaceholder: 'ex.: 32000',

    fuelType: 'Tipo de Combustível',
    fuelElectric: 'Elétrico',
    fuelHybrid: 'Híbrido (PHEV / MHEV)',
    fuelPetrol: 'Gasolina',
    fuelDiesel: 'Gasóleo',
    transmission: 'Transmissão',
    transAutomatic: 'Automática',
    transManual: 'Manual',
    power: 'Potência (cv)',
    powerPlaceholder: 'ex.: 286',
    drive: 'Tração',
    driveAWD: 'AWD — Tração integral',
    driveRWD: 'RWD — Tração traseira',
    driveFWD: 'FWD — Tração dianteira',
    drive4WD: '4WD — Quatro rodas motrizes',
    battery: 'Capacidade da Bateria (kWh)',
    batteryPlaceholder: 'ex.: 83.9',
    batteryHealth: 'Saúde da Bateria (%)',
    batteryHealthHint: '0 – 100',
    batteryHealthPlaceholder: 'ex.: 94',
    range: 'Autonomia Elétrica (km WLTP)',
    rangePlaceholder: 'ex.: 521',

    exterior: 'Cor Exterior',
    exteriorPlaceholder: 'ex.: Branco Mineral Metálico',
    interior: 'Cor Interior',
    interiorPlaceholder: 'ex.: Preto Sensatec',

    warranty: 'Garantia disponível',
    serviceHistory: 'Histórico de serviço disponível',
    delivery: 'Entrega em Portugal',
    warrantyTerm: 'Prazo de Garantia',
    warrantyTermHint: 'ex.: 12 meses, 2 anos',
    warrantyTermPlaceholder: 'ex.: 24 meses',

    tabPT: 'PT (principal)',
    tabEN: 'EN',
    tabUA: 'UA',
    shortDesc: 'Descrição Curta',
    shortDescHint: n => `${n}/250 caracteres — exibida nas fichas do catálogo`,
    shortDescPlaceholder: 'Resumo breve exibido nas fichas e resultados de pesquisa…',
    fullDesc: 'Descrição Completa',
    fullDescHint: 'Exibida na página de detalhe da viatura',
    fullDescPlaceholder: 'Descrição completa com todos os detalhes, histórico e destaques…',
    shortDescEN: 'Descrição Curta (Inglês)',
    shortDescENHint: n => `${n}/250 caracteres`,
    shortDescENPlaceholder: 'Versão em inglês da descrição curta…',
    fullDescEN: 'Descrição Completa (Inglês)',
    fullDescENHint: 'Exibida quando o idioma do site está em inglês',
    fullDescENPlaceholder: 'Versão em inglês da descrição completa…',
    shortDescUA: 'Descrição Curta (Ucraniano)',
    shortDescUAHint: n => `${n}/250 caracteres`,
    shortDescUAPlaceholder: 'Versão em ucraniano da descrição curta…',
    fullDescUA: 'Descrição Completa (Ucraniano)',
    fullDescUAHint: 'Exibida quando o idioma do site está em ucraniano',
    fullDescUAPlaceholder: 'Versão em ucraniana da descrição completa…',

    equipmentList: 'Lista de Equipamento',
    equipmentHint: 'Equipamento completo — um item por linha',
    equipmentListEN: 'Lista de Equipamento (Inglês)',
    equipmentENHint: 'Tradução em inglês — um item por linha',
    equipmentListUA: 'Lista de Equipamento (Ucraniano)',
    equipmentUAHint: 'Tradução em ucraniano — um item por linha',
    featureTags: 'Destaques',
    featureTagsHint: 'Destaques curtos exibidos como etiquetas (pressione Enter ou clique em Adicionar)',
    featureTagsPlaceholder: 'ex.: Apple CarPlay, Câmara 360°…',
    add: 'Adicionar',

    youtubeUrl: 'URL do Vídeo YouTube',
    youtubePlaceholder: 'https://youtu.be/... ou https://youtube.com/watch?v=...',
    invalidYoutube: 'Ligação YouTube inválida',
    uploadImages: 'Carregar Imagens',
    uploading: 'A carregar…',
    imageCount: (n, max) => `${n}/${max} imagem${n !== 1 ? 'ns' : ''} — passe o rato para definir principal ou remover`,
    noImages: max => `Sem imagens — JPEG, PNG ou WebP, máx. 10 MB cada (até ${max} fotos)`,
    photoLimit: max => `Limite de ${max} fotos atingido`,
    photoLimitTrim: max => `Apenas as primeiras imagens foram adicionadas (limite de ${max} fotos)`,
    setMain: 'Definir como Principal',
    mainBadge: 'Principal',
    remove: 'Remover',

    metaTitle: 'Meta Título',
    generate: 'Gerar',
    metaTitleHint: n => `${n}/60 caracteres — exibido no separador do browser e resultados Google`,
    metaTitlePlaceholder: 'ex.: BMW i4 eDrive40 M Sport 2023 – TurboEagle',
    metaDesc: 'Meta Descrição',
    metaDescHint: n => `${n}/160 caracteres — exibido nos snippets de pesquisa Google`,
    metaDescPlaceholder: 'ex.: Compre um BMW i4 eDrive40 M Sport 2023, 32.000 km, 286 cv. Histórico completo, garantia disponível. Entrega em Portugal.',

    errBrand: 'Marca obrigatória',
    errModel: 'Modelo obrigatório',
    errYear: max => `Introduza um ano válido entre 1980 e ${max}`,
    errPrice: 'Introduza um preço válido superior a 0',
    errMileage: 'Introduza quilómetros válidos — 0 ou mais km',
    errFuel: 'Selecione o tipo de combustível',
    errTransmission: 'Selecione a transmissão',
    errStatus: 'Selecione o estado',
    errShortDesc: 'Descrição curta obrigatória',
    errShortDescLen: 'Descrição curta não pode exceder 250 caracteres',
    errPower: 'A potência deve ser um número positivo',
    errBattery: 'A capacidade da bateria deve ser superior a 0',
    errBatteryHealth: 'A saúde da bateria deve estar entre 0 e 100',
    errRange: 'A autonomia deve ser superior a 0',
    errMetaTitle: 'Meta título não pode exceder 60 caracteres',
    errMetaDesc: 'Meta descrição não pode exceder 160 caracteres',

    uploadFailed: e => `Erro ao carregar: ${e}`,
    savedOk: 'Viatura guardada com sucesso',
    saveFailed: 'Erro ao guardar viatura',
  },
}

export default a
