/*
 * MySQL schema (future migration):
 *
 * CREATE TABLE cars (
 *   id            VARCHAR(100)  PRIMARY KEY,
 *   name          VARCHAR(200)  NOT NULL,
 *   tagline       VARCHAR(200),
 *   brand         ENUM('bmw','mercedes') NOT NULL,
 *   fuel_type     ENUM('electric','hybrid') NOT NULL,
 *   price         DECIMAL(10,2) NOT NULL,
 *   year          SMALLINT      NOT NULL,
 *   mileage_km    INT           NOT NULL,
 *   status        ENUM('in_stock','incoming','reserved') DEFAULT 'in_stock',
 *   financing     BOOLEAN       DEFAULT FALSE,
 *   warranty      BOOLEAN       DEFAULT FALSE,
 *   hp            SMALLINT,
 *   engine        VARCHAR(50),
 *   drivetrain    ENUM('RWD','AWD','FWD'),
 *   seats         TINYINT,
 *   img           VARCHAR(500),
 *   created_at    DATETIME      DEFAULT CURRENT_TIMESTAMP
 * );
 */

export const OLIMP_CARS = [
  {
    id: "bmw-i4-edrive40",
    name: "BMW i4 eDrive40",
    tagline: "Electric Gran Coupé",
    brand: "bmw",
    fuelType: "electric",
    financing: true,
    warranty: true,
    price: 52900,
    priceUnit: "unit",
    seats: 5,
    gearbox: "Automatic",
    luggage: "3 bags",
    year: 2023,
    engine: "Electric",
    hp: "340 HP",
    topSpeed: "190 km/h",
    mileage: "38 000 km",
    mileageNum: 38000,
    status: "in_stock",
    drivetrain: "RWD",
    range: "590 km",
    img: "assets/hero-car.jpg",
    gallery: [
      "assets/hero-car.jpg",
      "assets/luxora-zenith.jpg",
      "assets/velox-horizon.jpg",
      "assets/brand-1.jpg",
      "assets/brand-2.jpg",
    ],
    description: "A premium electric Gran Coupé with refined performance, modern technology and everyday comfort. The BMW i4 eDrive40 combines sporty dynamics with a long-range battery, making it ideal for both city driving and longer journeys across Portugal.",
    features: [
      "Battery health verified",
      "Warranty available",
      "Financing available",
      "Curved display with iDrive 8",
      "Heated front seats",
      "Wireless Apple CarPlay & Android Auto",
      "Adaptive cruise control",
      "Parking assistant",
      "Sport seats",
      "19-inch alloy wheels",
    ],
  },
  {
    id: "bmw-ix-xdrive40",
    name: "BMW iX xDrive40",
    tagline: "Electric luxury SUV",
    brand: "bmw",
    fuelType: "electric",
    financing: true,
    warranty: true,
    price: 74500,
    priceUnit: "unit",
    seats: 5,
    gearbox: "Automatic",
    luggage: "5 bags",
    year: 2022,
    engine: "Electric",
    hp: "326 HP",
    topSpeed: "200 km/h",
    mileage: "52 000 km",
    mileageNum: 52000,
    status: "in_stock",
    drivetrain: "AWD",
    range: "630 km",
    img: "assets/velox-horizon.jpg",
    gallery: [
      "assets/velox-horizon.jpg",
      "assets/hero-car.jpg",
      "assets/luxora-zenith.jpg",
      "assets/brand-2.jpg",
      "assets/brand-3.jpg",
    ],
    description: "The BMW iX xDrive40 is a flagship electric SUV built on a dedicated EV architecture. A spacious cabin with premium materials, long range and all-wheel drive make it one of the most complete electric vehicles available on the market.",
    features: [
      "Battery health verified",
      "Warranty available",
      "Financing available",
      "Panoramic glass roof",
      "Harman Kardon audio",
      "Gesture control",
      "Adaptive air suspension",
      "Surround-view cameras",
      "Heated steering wheel",
      "21-inch aerodynamic wheels",
    ],
  },
  {
    id: "mercedes-eqe-350",
    name: "Mercedes-Benz EQE 350",
    tagline: "Electric executive sedan",
    brand: "mercedes",
    fuelType: "electric",
    financing: true,
    warranty: false,
    price: 63800,
    priceUnit: "unit",
    seats: 5,
    gearbox: "Automatic",
    luggage: "4 bags",
    year: 2023,
    engine: "Electric",
    hp: "292 HP",
    topSpeed: "210 km/h",
    mileage: "29 000 km",
    mileageNum: 29000,
    status: "in_stock",
    drivetrain: "RWD",
    range: "654 km",
    img: "assets/luxora-zenith.jpg",
    gallery: [
      "assets/luxora-zenith.jpg",
      "assets/hero-car.jpg",
      "assets/velox-horizon.jpg",
      "assets/brand-1.jpg",
      "assets/brand-3.jpg",
    ],
    description: "The Mercedes-Benz EQE 350 brings the comfort and refinement of the E-Class into the electric era. With a long-range battery, a sophisticated interior and advanced driver assistance technology, it offers a premium ownership experience.",
    features: [
      "Battery health verified",
      "Financing available",
      "MBUX Hyperscreen available",
      "Burmester sound system",
      "Ambient lighting 64 colours",
      "Rear-axle steering",
      "Active distance assist",
      "Wireless charging",
      "Air suspension",
      "20-inch AMG wheels",
    ],
  },
  {
    id: "mercedes-glc-300e",
    name: "Mercedes-Benz GLC 300e",
    tagline: "Plug-in hybrid SUV",
    brand: "mercedes",
    fuelType: "hybrid",
    financing: true,
    warranty: true,
    price: 58200,
    priceUnit: "unit",
    seats: 5,
    gearbox: "Automatic",
    luggage: "4 bags",
    year: 2023,
    engine: "2.0 PHEV",
    hp: "313 HP",
    topSpeed: "235 km/h",
    mileage: "18 000 km",
    mileageNum: 18000,
    status: "in_stock",
    drivetrain: "AWD",
    range: "134 km EV",
    img: "assets/brand-1.jpg",
    gallery: [
      "assets/brand-1.jpg",
      "assets/luxora-zenith.jpg",
      "assets/hero-car.jpg",
      "assets/brand-2.jpg",
      "assets/velox-horizon.jpg",
    ],
    description: "The Mercedes-Benz GLC 300e combines a turbocharged petrol engine with a powerful electric motor for exceptional efficiency. With over 100 km of electric range and the flexibility of a petrol engine, it is ideal for both urban driving and longer trips.",
    features: [
      "Battery health verified",
      "Warranty available",
      "Financing available",
      "MBUX infotainment",
      "Panoramic sunroof",
      "Heated front seats",
      "360° camera",
      "Active parking assist",
      "Trailer assist",
      "20-inch alloy wheels",
    ],
  },
  {
    id: "bmw-530e",
    name: "BMW 530e",
    tagline: "Plug-in hybrid sedan",
    brand: "bmw",
    fuelType: "hybrid",
    financing: false,
    warranty: true,
    price: 44900,
    priceUnit: "unit",
    seats: 5,
    gearbox: "Automatic",
    luggage: "3 bags",
    year: 2022,
    engine: "2.0 PHEV",
    hp: "292 HP",
    topSpeed: "235 km/h",
    mileage: "41 000 km",
    mileageNum: 41000,
    status: "in_stock",
    drivetrain: "RWD",
    range: "98 km EV",
    img: "assets/brand-2.jpg",
    gallery: [
      "assets/brand-2.jpg",
      "assets/hero-car.jpg",
      "assets/luxora-zenith.jpg",
      "assets/brand-3.jpg",
      "assets/velox-horizon.jpg",
    ],
    description: "The BMW 530e brings plug-in hybrid efficiency to the acclaimed 5 Series. With nearly 100 km of electric range and the performance of a turbocharged inline-six, it is one of the most balanced hybrid saloons available for the Portuguese market.",
    features: [
      "Battery health verified",
      "Warranty available",
      "Live Cockpit Professional",
      "Driving Assistant Professional",
      "Heated front seats",
      "Parking assistant Plus",
      "Harman Kardon sound",
      "Wireless CarPlay",
      "Adaptive LED headlights",
      "18-inch alloy wheels",
    ],
  },
  {
    id: "mercedes-e300e",
    name: "Mercedes-Benz E 300e",
    tagline: "Plug-in hybrid estate",
    brand: "mercedes",
    fuelType: "hybrid",
    financing: true,
    warranty: false,
    price: 47600,
    priceUnit: "unit",
    seats: 5,
    gearbox: "Automatic",
    luggage: "5 bags",
    year: 2021,
    engine: "2.0 PHEV",
    hp: "320 HP",
    topSpeed: "250 km/h",
    mileage: "58 000 km",
    mileageNum: 58000,
    status: "in_stock",
    drivetrain: "RWD",
    range: "108 km EV",
    img: "assets/brand-3.jpg",
    gallery: [
      "assets/brand-3.jpg",
      "assets/luxora-zenith.jpg",
      "assets/velox-horizon.jpg",
      "assets/brand-1.jpg",
      "assets/hero-car.jpg",
    ],
    description: "The Mercedes-Benz E 300e estate offers a generous boot, a refined interior and over 100 km of plug-in electric range. A practical, premium choice for families who want efficiency without compromising on space or comfort.",
    features: [
      "Battery health verified",
      "Financing available",
      "MBUX infotainment",
      "Widescreen cockpit",
      "Burmester sound system",
      "Heated front seats",
      "Reversing camera",
      "Active brake assist",
      "Roof rails",
      "19-inch alloy wheels",
    ],
  },
  {
    id: "bmw-x5-45e",
    name: "BMW X5 xDrive45e",
    tagline: "Plug-in hybrid SUV",
    brand: "bmw",
    fuelType: "hybrid",
    financing: true,
    warranty: true,
    price: 79900,
    priceUnit: "unit",
    seats: 5,
    gearbox: "Automatic",
    luggage: "5 bags",
    year: 2023,
    engine: "3.0 PHEV",
    hp: "394 HP",
    topSpeed: "250 km/h",
    mileage: "22 000 km",
    mileageNum: 22000,
    status: "in_stock",
    drivetrain: "AWD",
    range: "87 km EV",
    img: "assets/hero-car.jpg",
    gallery: [
      "assets/hero-car.jpg",
      "assets/brand-1.jpg",
      "assets/luxora-zenith.jpg",
      "assets/velox-horizon.jpg",
      "assets/brand-3.jpg",
    ],
    description: "The BMW X5 xDrive45e is a flagship plug-in hybrid SUV combining a powerful inline-six with an electric motor. A spacious, refined cabin, all-wheel drive and BMW's latest technology make it one of the most sought-after premium SUVs in Portugal.",
    features: [
      "Battery health verified",
      "Warranty available",
      "Financing available",
      "Panoramic glass roof",
      "Bowers & Wilkins audio",
      "Gesture control",
      "Air suspension",
      "Driving Assistant Professional",
      "Heated & ventilated seats",
      "21-inch alloy wheels",
    ],
  },
  {
    id: "mercedes-eqb-300",
    name: "Mercedes-Benz EQB 300",
    tagline: "Electric family SUV",
    brand: "mercedes",
    fuelType: "electric",
    financing: false,
    warranty: true,
    price: 46500,
    priceUnit: "unit",
    seats: 7,
    gearbox: "Automatic",
    luggage: "4 bags",
    year: 2022,
    engine: "Electric",
    hp: "228 HP",
    topSpeed: "160 km/h",
    mileage: "44 000 km",
    mileageNum: 44000,
    status: "incoming",
    drivetrain: "AWD",
    range: "419 km",
    img: "assets/brand-2.jpg",
    gallery: [
      "assets/brand-2.jpg",
      "assets/brand-1.jpg",
      "assets/luxora-zenith.jpg",
      "assets/hero-car.jpg",
      "assets/brand-3.jpg",
    ],
    description: "The Mercedes-Benz EQB 300 is a fully electric compact SUV with an optional third row of seats. It offers a practical and comfortable solution for families looking to switch to electric mobility with the reliability of a premium brand.",
    features: [
      "Battery health verified",
      "Warranty available",
      "7-seat configuration",
      "MBUX infotainment",
      "Heated front seats",
      "Reversing camera",
      "Active distance assist",
      "Wireless charging",
      "Privacy glass",
      "18-inch alloy wheels",
    ],
  },
];
